apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgresql-db
  namespace: plenartrend
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:16

  minSyncReplicas: 1
  maxSyncReplicas: 1

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser-secret
  
  storage:
    size: 10Gi
    storageClass: hcloud-volumes
  
  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: preferred
  
  postgresql:
    parameters:
      max_connections: "200"
      shared_buffers: "256MB"
      effective_cache_size: "1GB"
      maintenance_work_mem: "64MB"
      checkpoint_completion_target: "0.9"
      wal_buffers: "16MB"
      default_statistics_target: "100"
      random_page_cost: "1.1"
      effective_io_concurrency: "200"
      work_mem: "4MB"
      min_wal_size: "1GB"
      max_wal_size: "4GB"
  
  bootstrap:
    recovery:
      source: postgresql-db-v2
      database: plenartrenddb
      owner: admin
      secret:
        name: postgres-admin-secret
      recoveryTarget:
        targetTLI: latest
  
  externalClusters:
    - name: postgresql-db-v2
      barmanObjectStore:
        destinationPath: s3://plt-db-backup/postgres/backups
        endpointURL: https://fsn1.your-objectstorage.com
        s3Credentials:
          accessKeyId:
            name: hetzner-s3-credentials
            key: HETZNER_ACCESS_KEY
          secretAccessKey:
            name: hetzner-s3-credentials
            key: HETZNER_SECRET_KEY
  
  backup:
    barmanObjectStore:
      serverName: "postgresql-db-v3"
      destinationPath: s3://plt-db-backup/postgres/backups
      endpointURL: https://fsn1.your-objectstorage.com
      s3Credentials:
        accessKeyId:
          name: hetzner-s3-credentials
          key: HETZNER_ACCESS_KEY
        secretAccessKey:
          name: hetzner-s3-credentials
          key: HETZNER_SECRET_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"


