---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: hetzner-s3-credentials
  namespace: plenartrend
spec:
  encryptedData:
    HETZNER_ACCESS_KEY: AgCzc4Nl0eQ3sbdLes65jZnJFufXOOpF10nAt9ZtuVk80JJOcnK9UMIFjOxW76sy65/H98SJBqiyEeUxJBzIG9b5eIqwwuCCiZWsoWn0TaHRhAFdmiHfeMwTrREo7bphycFTrC18VKHpWWdJttVHhPP207VBtSGl+N5Na5L4uLU2KuwVfcNz3Dx5SYoNJy0mN90UtMBc/GRul0E8NLIxmXFG/5WT0w5Dw0yHUyUNjzzBcNdHIIA0I5DzsdHVQZhlqsMQbdZjBVF3ukCAtDPn0ilKBF14Oov4LA3qqpc6htTf3v8pn+7jphMmEe/oC5/wA6pIdYkCh4WjIFXMY/9QvasgKsWALEUvco4zzns5n0za0gOLBwUGsTk6giRW0dvXuPF7Z0/V+6QzMK7VhqOmPkfD4nbk8nla2j2XF+PqFfigp16q3V4enSj6LqR3XUZ5gK85uTCKJ7A4b5He7OV88rshvFOg4dupKVmTF6ikX+WT1ecjq7qo9094H/eOf9DxYbUTXerU3diyFp6gsoLjSkOBi2ASiwK0jB/oHeGteWegx116BNtMdocJGZ6neJXzenQUthglFOSHZBY1czbaYuroiCc8031TwWrYMemUAAkkXTH7NADk5ylqCKN35QRVCV1VDzYxi/jGZaVHcbMUVHeT62tNzYcCBX7n9UXqKQf0zMumsNSIuJeB9DCUfTmz4CKZwzCbYNKxpxvr7E3nsG5RMmWBxg==
    HETZNER_SECRET_KEY: AgBl3IkWMA5MYNOlxNQkuJYH6j5cCPL81YOkZuoqigAKS4L0qe8N6XXYM6GBjxr6o3+PZLWnK4cSccqVSOP2Lj3fx9+Kszr5k2R92j6w+RdJcdIx2KJrjRecJrIhWex83tpargAEhRfUjRt5AeWQIWvRX8+joYwdrQzpmMRqBwyM2ePNehwV/WC4zcz4yztS8gIv6r4Ld3JQel23vNH7POokbkbxCTVT0mD46GOfIsPYsTLYMb9UBDPBU0oYSj5JYfdyaROrxmVMPWGGF8tYbby+P3yq597/qMRoN/v9laGQnCTUiqxHbV3fvA1aW4jU+MJ61LlNr01f24Z9mLttvfHaoLGT5uGM7UX0N3xP8qozUzkVIgLZg1Vy/n+3AKIQdijyVrhw9RVXpSguu5xsH1Pf/ExwwqOMtEmB5y5N6XpP4EMRxURWj3flkjc8c5KGz6uJMYslLq9+Qh/+GXRy+8aGVppVK4EO6L5fbU64gDzlZ2VkwxjsbHA3OHbYFCjcY5OFHwDbbdER0puHq4qmcO4+gMojFIEdqqfy9O5NXi71hP4SQ5Xzsm3+w/r983xt1iSQOCOtj24e++/GwZ0utLlFhg+sexN7lgMHeqavh1wg0QaZWlCE0TSMgrSw2sGsd3emlk9roTfy6GnfEVX5ZkCgKLmsKFEZFIoR1gwjbMdViC4HFhYHkoD1uLNdSEJTu4OAxsTiv3abfWvwdjQtV9igLq3cWBtxYMcEYUzgcCnFsgFWL2epxLoL
  template:
    metadata:
      name: hetzner-s3-credentials
      namespace: plenartrend
    type: Opaque
