---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-secret
  namespace: plenartrend
spec:
  encryptedData:
    password: AgB+YiwyYiyfFek92iork9fYUpHY9ch/S+WYcrYOGo44qIcmP+jeiJmcCq83b3XqQDmKMCqiyUFZj7Ri+JDlUTD9iJT/uwOWTOkH6VPLHwkdO9m9AHJKVSukaxQpvwu1Bkyq+auoZZn2Lt20feNWmWOeA7p9tps6yOMXBX1CX6Pzk7wpPe8cw8gJDTXlDNmej4OIzMFIIuAGGIWqcClrSJBKZOZnZ5jcScrosU9daRk8d91pjhtmLvd3qZgK+1wDD0KAEWIlGyUWsQuT0bl4stj6wsIdPLFMeRtzNmC0w1h88u1nEI2+e39m0GKtvdm+vHonryz1p28wODH35MYivDAPbkJQdBRkfBKmWu/OusBbck4g5Ko9th9nAKEM7VhFo0TZS0EK7LkXOP/lyozZyMVUdvk0G282c+hdJ4CpKCISFWHov/ApGpzTC1lP5Uv0VPNU3lBqgK76/Q8hGhV0x2tXAI5lXtB0Eau1G+EV4L1IjxRpLSrpIea1kVD/t+ArBkgjILms/i4X0nZgClkqbzUo7GUENkPzUAIM5PCGyA/G/QYmA61W69xfwNWM5pNALrBmeX5wJO4WY2kiDXrB9c6OZAKB+4R8HOf1TUXZdf9WdualYrSoUoqFlAZI6Edtok+T4mVtU8iqB5vLiZTiQjlTHY6Ku/eVRVL9S2+DqRdCO31+H3Z8NqzYQM7JM6mxEENFFQV9V2g53vceY+QUBO+3drGG+g==
    username: AgArv+9FtaNntWi/w196pkwokgcGccnZ/QI643JBz3EZNeFAfwyOx2UAa/ikPGA/Y+1Gj9DwHibTP3gfIXIAgA2RQWSNx+bPyOQrwguh1kxuFLc6KoNSCPO+pRYEotyDBOmA44c9iB3FQjfqVSsRfTlCnmv7F8y87hrXnFQG3LdfS2A7sU7Oqgh1OiApbcQv29lAkBW3G29Lxt5ouAX0tpYCP+F/h+p5HQWR6I0C0z/CAcpCienjN04BUoaN1B94DmycmXNQFs3AzDw8IqL1DYISn5vjzOT2f8N/t3T3kPTVvVC7f94T8+mwIIuIEBlgOidDm/MwNA1kzH6vnmw5hCHmyHsiUz3yDCD/2lr2UBbYhSGRlFLgYSAe27kpoG/vtFZn4wlZmFHM0cjA2JYyH1bU8fN5oZ/Xw0A/+XCGaru2cE4lnF6NgyIDSPPQb7aRdm71GWlrxpHYJOpi/OuhVZhSG3UcURvgcuUwdOMXnDuVXrOgSzKfyJQyA54hueYDmEAryM+TmKYc/u2lT4ppZ6QJZO3l1Qn6dNAgEHrYnBtsM7xbcZSsDPg8dUradomCh41BESvc0N2TzmHucugTn1SX8BcqXJrZvT37sKV032eajQ9kiWIkqT0dVoqpVVySbf7FLUj3TbwinP0AAelwKcnNvsFQTuazJjTmTul31hKDyC6OeBapgIkb4ync9R+n5Ilo9vb7fA==
  template:
    metadata:
      name: postgres-admin-secret
      namespace: plenartrend
    type: kubernetes.io/basic-auth
