---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-secret
  namespace: plenartrend
spec:
  encryptedData:
    password: AgA68Vurg2Jo4zG/PsdAInfHzN8O8GCm0nRXtf3C8WF8bnHXb5ONLvWvjBp0aTyaVvZol32ZSnYUEgVDACjCeCgBuvRTx/0rD7VZpLtkmoni3+gJmfQUGFh0PecChOHhxnZ+mVVnTSqqLBYIYQ+GeP5QqxyUbFc9Idjx9albYGuP2VCZUXHS2Txabj2X8HG7Q2y3EWLfKX85rXeiB9EvK3V8qZ8VI4zHRTA6kvza/Lk32+T1l+bL6S4CrkO/V6PfhRqMqstb2lSPC2YM5zV8Jl9DklZZQMcL7kxeadvdqXw22PTnMd/veZOxouiYEIwZ65dXiAj9fR95AyjbflFmKQC5lDSLD5k/DSX2na4tZ/ccH412OE+Y6uYUH2HmXadqXYggacTgEOUS8wpjRDKDDVGhkW7oqQNMFOV51AGgpRKCu24YjQfditIrH94TOznd92G6LsNe/FIvtB/BZhvort4t7dnj5NEDVtbWzjk9HGE/AzPV9uhlVydHqMoNyAZcDgzzCF1wrx2gYe3W9pSInlTiK8NrLPE4xRECVa6yTnrubWOsYhAWBxplL6Ru/3UcJ9PipdAPciqKBn7ZD6nwBQiBw7Mge6HiApdvlUHCmuW3ZPilZ75oyka0zMvS5p/a/bs9dcEd5GduvTHloP5onG8TbwgWWCMgPAe0XbdggOXX/dyn5ZsS8M2fsn9hNcqUhuN993fab2TZPhFCPRBiN7OKnvB2Zg==
    username: AgBclWdGbGHTkIHTXvIQEcEezevtKK5YhDL6ehms2hYoyreWxV2zLJaK4outQaPHkEw2cdemZAshni4CBSNeDKsfaZb3isZJv+aw2epUUlEhVNk3p08T4h4/EC2GNfHl4prI1VdQ6wJffvTngkFmgBoCK9QzYRLLXjELIJTrF7oI1Bnbg9TX7NUjxjtj60SwcH0igUGpnLswziSmSG8/InesJCA38ltjbwIL8fYkl/h7pGnlJrf3sFM+5wGTY3K6rKRqND9p525RWAWZeSetrWYr8sIgmm9Lb0LjnaGVK9NTZS0KDK2FzDyHRpR4UtX+f1SITOJzDuXUM0fWSmBJHb6mK56ZwHmO4XBMhBB69BRLME7sVTRWljmQitTmNAgqdEyNThOfggvayfVEx+6N7qw2Xzqc6CbIGrguiy66elt8YMyfn3txuLnfwT0Vl94I0yexMNv8c33fq5M6dv0A5qeySYtsj+uVzts252AU11QriX7+jG2/zqqHPdPidRAx4DOYDr58P+XH33DtbGJh2jZitxJJKP/pMtgcW03T+gguKF7lgkSezXxIOiia4516BYANJiahX/S3jWYkzTgKbiwWV/2DLB/UHYQYeJPNDAR04GUYfEBOn3GNucVnd0JeQoQoFjUYsGljekJZrIaI+rjPAs9YmSthmaFy7srBiuW3WmY9Ku+/iI5xQTteoh+YnkOiJw7+LA==
  template:
    metadata:
      name: postgres-admin-secret
      namespace: plenartrend
    type: kubernetes.io/basic-auth
