---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: plenartrend
spec:
  encryptedData:
    password: AgBsKH/UnHAm4dz32k51DsiOa8NSWIFKRnJsU8d0w4ejml76HWLWYtZojXwiYfDOaxVPrDqmHGG8fA3P2KYBv1oxZqJgFqBeL2KZGUvwTiwnUlhum9H+/meqD894AHdXyTVekiq6l1k7vEXruhvdgkvWFx6OsRXx1Uw4FOygSIvHDcZKcrMs2YzIIDyoUlWjnNDsZa2Z5Kza2p8tkCNY+bBnl3l/tiDeGK7IoRjliLcs6heqnkUR4wgNWtcJL5u7BCIw3RfUWRSNysxOIEylQWOxB31AniMX63xiNkSUSy3s0d1SD82XfFlIxfU6fiu3wZNDgpTSZh6MhXU2kGSQ6UeWY6TS4UeEyawgZsclOeOnD80ooY6xx4K2t6t0ZD2BB2CVlfwB0ZFWbYpZf869DTcqK1biyoS3aqh5c8ahnVNqSC4DhQ4bXqg6JU5gBK7tHh0qI6imYezNmfemNOKxOXZoSCfePqWjZNjREMvrlAVFlHEcgNPjJh0BbglEoRElwY0Py99YOiIYSaAX2cQ8YPSlasgB80c9lfylvQcEuo2YtWTUd6kxyUjWyE4gITFW6YVgboE+xtCTgN8AzpLnw769obO9HfMD6wE+ZU6LNF/2LOnUwgeXka1Djf/S1zXhT9ui4NJoMWk82I+pBww/WAYsVYxI8F2ByURaaR0JwiGYDTnkrxk9nxNb+myQ+/XltzSyPuXCI/dxPV5oZL0orlldJeAaZw==
    username: AgA+nYnEOlRwUz6ODUaSH+80i/MHPaHnuV0BMnN3b9l8KWvjdt++SKQhKbUVmxjN+LfbqAeG943ajxzGFzGxR+eeb7i4IidIXqtJsiZ4vXZn5w48vAiEk92mnWtwZyxiuDXakpr1Z1DsOo0M0f7m/lexlRkzkNbvlF1K/jkRobpT1QkCX8ZZRHGL+LYZ4r4zvzNiMIgP3EXTzqIaHRRV/htHb4Kt7fIof6HMCKsTZAguyqJhp5uR1c0uR0RhWMHcwgUI4Ikhgn9v4mrw+bfGQgUTepZP/kojdpmLbkfGaYy2SEKFy0lFE/AOPK+3n0NevzUNLXrEw+dSzPwmqOLJVCOmpjx2Gf+tqHteff+RaDVRuHKCWpbRUKBfPZZ7OJ1raigPd+HJXNPNzKmyS13PV3Wt3Xpr68UHnm41ApO9Ji6tpvdHMeFrWKPF1NLKe5GxRDl5hzm3Z75mAdvZQTzEWH2tBkgzS4wPMHh/2iJf5w9k08Q3UahsaLWHoR7m1udav7j3R617PwOXgGP5dk0Q9o2GaL818f71RXa817n2CwO80dbaP6LvSdXrbFMnekWsBZqmDMiAGMvtHI6zvVMgxzFmi/sVaqOd85lfu2csmo4Sl+tVjmUTZL+NaDq+iOiyC2P/MFWhPkMoaU9+ORZ4l4oYWcBgtbeQOv53I3TX5fUMjks8mo6JtlX4YAOdBhvp17O2ch8JVCdYUQ==
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: plenartrend
    type: kubernetes.io/basic-auth
