---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-admin-secret
  namespace: plenartrend
spec:
  encryptedData:
    password: AgBt3+QwAmkb7Xiivj4ljSCQrCt2Y2EgPDmTI/inBbqI7Gr2PPyDArC6mOMhtzHoIGCTLrZo6InXSbosTFZS2UzOvAi0bRFjsJjo3gvErHXjqjlXpctRsSMZuDTCJrNOOcmUF3+nEwtvizfpGSjO8jKg4oisVCh33HwDGcfKYmOISONBJONXl6Tdemgax0BjflU+S3luEc9LHqMVYcRCefL7oFEuDOGC4VvDKOLAGJ08M5Dsxd4KWj3UlKRxiNtZaM5jEjRsufLxJupF5OI0ZoO6xDzuJimD0F2IMsbKJ9vcedLbBfjhbgKAKBl5MnYcaZuB0WRBYRnIus8yOM9fknnwKgI9VNk3W8XeQGsjQ0JAddFlUeRWw2zWsGtFJwN183volY5NfAAwBtNAOrxhDyb4VWPqHc7LQU8JbU79go+X3Kj7NQwZYHgOJ4xVFeaj8rWfoD0LqY+5dCNi6C8RjPG0muzSbl2ZCcJg/8/tW30ePhfamaTmyeSpfEjvwSyq+tHGxUjA1xz/cE+DaYcL52RzXFRiHxqdalgrwbbP9U1RKQeJrpqwRS2+goS+g5rkETdUpR5qbYui+3CJmHsMH9n+gLyqm+9Ssdxt+BCPqXigdPNwdjSqXQAsS9cYr89/b9cMGUEFSi5ol0wjSShs8xlDmIKt/XFiKMzG8T9ZXWoRp8z8IPrlym/VaxOm7BHpeI3YFN+aJx4SN2WUTb+IWIifomcsXg==
    username: AgCcz5X8F3JLSVANsWBi5R7DcTgyz5GnVezKAX9/UGtrZ7DVgCPaEtzVD+LVn3YNZW0Ova6B55KM6X7qAH2WE3swLJDJHvOFx3oJgfz/tGWMiE9UNQW69FCgDhGv/YbFoETpuTEj34dvBnudU1DMIuBEb+5EcRlUNATK3zCH2alHp9hkAxSwMyqvzMMcKaHp8xVENgNgrvanqMgcEo7GWE6d5teCy0IW9kg1dG1zFK9i+iQNREcG496KK/fuuLc0ls+SEil4xQyAjQKsXbUbdv8d4OZkVR2WMim5+ToRjXH2/fjWoj7qgdcZKZOIkP/L4xzzze8y9M0rEWyl08XLCZB6FLAqLdV3D4o6ufDiS2VEFfw5s6+hVcJyMSfSpCzXgpmR1QwzmRhtVVn7bl+NdGpPlOppVwxV1riWe8MJ0ZpiIiVahP1Ee+6UtukJrfi/PYvTjm+awPZdFtI6QnyaB29efrThhhnp1d5pWGCEpFzt9whMvLgGIVG8NxzSwiZpQ04YXr553W4UVc4HDgIrKE9iCZorP/JbcaJ3YMVkL77sepxKiZJEHF8Px25/dO408CTysJuFCudR1Jwuogc7EbdwI6PUT+2AyBW2NlqdrWD1IsJI8AWBcXlKFpxO9NUxqHEQVuem2y5iCnHu/wDCrKha7VpcxaSGXUX9PlE6kJpX+pZ9Jsvnv179dGqrVBirQIaOd4Gt8Q==
  template:
    metadata:
      name: postgres-admin-secret
      namespace: plenartrend
    type: kubernetes.io/basic-auth
