---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: plenartrend
spec:
  encryptedData:
    password: AgBdC3OuDqK+B+edOKlRRZy7a1HE0VCX5ilcJScnaxs6n46ZzXM/F4mh28xj8CIeJk0o0u1n17nlLbBu+v9CqRlnotVSVNxcf0ovZ8Mxqi+LZU23GFytHCT/pDMHbg2g6YR0Yw0cra7pbjybYHj1AXm3xD+QDn7gjgDoE4aEOghGc7pBoyYwVlXKIoVr8WoVVrzicHh0VJ3kbzqNeMSQhKpTLVGH/5O0fDfhrcUCQw26hyXbEi4qNaBUJpnv1Gydnfmp6Jo6i26GcaPS31x4Q9iJwuRWgNZ7dHGV1KYQvdQnenppNRXqopv2C+0UtkOBXZuUPmGfSR/+uiRvzjxSYXRu8Wok5xB4gr0Rg39voLakgK3GIuz9ty5tNJ98zRMr0avXZjWhRWAl4YYn9Rv3MqlEstCQZ7ynyn+DMcnOjVHgQYOfKNtwfwFZynUqIg5EAieOsPuLalcfyNwW00FjWceAx6BSJzUGWmO8S3Ytn+U1dBObk7vYANsbUVkgBaWVRBXobwqwjj5i3H1zh2xI6cwlAnEJamAdv46O3sHTM3LBHkRwFwkAlP4IcN/olTGgi0XiSJzCeHvKKdTd82zVZv0mMqLUCkljfZetcxjtc3veuaEf8SH7KtAvT0eXVJ97dOv4XXCmPIX9+zwERsaXXOLM/ZlPgzoVQB3/MHnzTs8yAGwM90yyFu3iuPzEoXdwHd6gTfQ0FbvjyGsiIwhX4HBX0K6eVg==
    username: AgB6U723oofRUf35lUdkI6sU0Aq6rmkVe3QbgCQXBaEX+sTm0kBK5veMLELNTz9fnq+kjYXEL1uwVPchMfWlBHl7DGOHyys8JhjAQQi01/cf2w/UWXciKY5oa30UPgjmBouvSbYQAWtyrnPhUoxqAFOh9yjJbCR+CA3nQXahSuT1GNrFGH2Q9fUsEMW9ZdXoiaJVjqCsbsx8Gqt/ZA9MDeKK4o8XkHHBXEK2Tps7AGGHXMwoQUdcXTmbzbZemJuPASOD5ejT4S9WATUp3DiMrCec775PeA25oKrkhoR+FHN7p6qZjUwExqIWeEa9wD45OzY8I54+VwV4D1TKyRazH55w6yPa1jiv/ep6InzXsBisxRZWYhHAOpDOQFh+wIZs10ySGG4vGiFMjrzl8Ls8nzKkJXUBt6UyXq9l5h1EkM2NZ5HtMDd2GULv2zbG/GvTpR/KTv+ig1pQWcD6a3o68xD5VyOtZ/Vi/G5A5U7MpyTIpxWqYzLfQHX9EhV+UsNaK4GsILQ3Fca/XSGrbInyygkIAWkkea04pRye2ZYAMhDNpq4iDmWLGovaQw6AimIGRtglXgZ0NsNCOP/V5ipMPSGAxsAdy+rYlLdDwTRwt1RhHM/NEqNxycfY32cgDdx4DBguNZuPZiqClPcWq9C3uyL9gOIk6Uq7uKYV+S0LYJ+lrk8cSbTQYVxPgboyoKgbZQAsBjcWvT4Tig==
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: plenartrend
    type: kubernetes.io/basic-auth
