---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: postgres-superuser-secret
  namespace: plenartrend
spec:
  encryptedData:
    password: AgAXI8DryJGLM6beAlzgyV/kqdmWhECcW1zHXiUdeV4PzWMdFuJk0P9gm+lS9533vgWIY0UHQP2pyg7UjvbqSblmr4VCcozg/uGmRQWf70z0kGaZYVEBQxG/yFS4IdhkjU2xqVvDvwlvZHPgYKjuvM+xT9uipLnuT8O9S3VdvE/rhGM3NExqgbhXCbxv3qbKXIHP/DhfDIq2nmLcO/UkVXhRYtN9AdOgYqVdYWnMo8B3j4whdAgesnLgJs4OyZKtFroerXmW1w9MaKvyTtgIrA0TIESYlZj/CtIN6T9tDPSRWDNZm6pjxRlzQaRhK/BzEecyyoBv/Iov4ZEeRkIfDlr3J5TF/EneZtgdWmNSWvpxzx1Ww+ZaL1EcnHDajPz374r5ZxXdzXmOTTscXNMXIReWWLthAQv+R68jcJy7OP1MyW/KtqpN4GC+SrUr/zhpWK3GXZJdjtHJ23s4Lumx9l/fWXGtfWNA6zM2YYbcfQ2sY6HUJ9GmIm/JazCHA0brk3FdBSfOPuTQX8Ro10dwRPJRp1HijVhidH9FdqZ6PcJZzN+8zYjcOF4JShpBhxitzkGamR4zlqlwUSm0r1HYZMQHolJ+Fz+QkJ4M7lL5ck3kQgzDA78GHh/g6XNcaz65dCiS4WJaXOCwgCoOtgF9Sk4IgUS4UgaCfdEeNEH96n0Fn2gVI0Xo2eTV+iYbWHV59+1795cmbTwcCQzVruPPTu1k5BfpQw==
    username: AgA8y9A1Hv2RkuMbGNoLA1+rolCq7q4IUujvVm3U+Atn/mKxzSZGCe0BKO8e5mlblrYp82+2AlQPQ5DQbs9l+e1X1vBosLqfreifcWWRfhWXuBQnMu/vvq1pDKzre01601/kdggY1Rek5m7crenZK15HQuFdmO1FWtvva8gIZgoyl/LJJneDwFEyvZ5ji/klHIfKdmrHXExHBL6SGiICKOUNd5v87IKTMNh7HvF5orNXpNO5prw/rFc1S4JKXueC3dGj/xHyb5tLTx/Axjo/BeBjnFFTx0WsApK3rhepVEiztNnV5ANoAcl83CsjECFUOxBuROXMkeayRucmrOlfJaJvX5nsU9iTZlFsfacPNmkEGwETBauoXktXLpYYwELqxWq2W1DTowwzaY2q3Z4+xYywE9rmV2CcaU3K3xIuD3uxlZCERhu4wrEJwYgIiua9y4VkkOT2HLWFa/NZBy9rM8eqJ7Im1533nzHbjP3q5hEXjPdRov2+aWnw/790igmbc/xuclG0ShWr8d5xNb1lrupLwd4Y9S7I6QuUoO2WXHNsUjaYnfrzd6iYtmPCKpHDuvidgkjw+2HKIoSw6Vmv+Zq/9ZvAxfSTWhJIfOY4joDXfMsQWwYX8gNCEIbJbcTre1CatAxOCZoqkuJlMxRYpS/vsagP7VJIhBlyuC1/nPSEQXS5oyEKrWI2R4JDgzk+Wezeu3cqbkPQ7Q==
  template:
    metadata:
      name: postgres-superuser-secret
      namespace: plenartrend
    type: kubernetes.io/basic-auth
