apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: docker-registry-secret
  namespace: plenartrend
spec:
  encryptedData:
    .dockerconfigjson: AgBLg3zw5KDlSmLr9FHaJfec5s6o0kWtf8WypkfY2q97qwHHFOMvOhW30OUcM/VFau5WfApkj62u0HGBtovEFnRlTVAnSZGJAdpuiZLw0EeTIdXk46c7QT+NWQIfUs1TkOG/OwJlUSwTpxmE64xaXscApPytnkYu/1lbkhZVSZmNROglsaejWiqHDGBpcZJgdSNlp1+IuYmPn0h7EWAUemWGswHylQeXUWdNVM8hjxu5CtfNRny2vwcIwgOkp83iS839wRjDIFigRsCxA3qUerR22rk5zMf8ln3CulSgi/pXxH+Dg2bZe0B1NsOeDC86w6gMyARv7lFKy2vl4JjeaZfjVew0o4mhZuPIp8E3QGbaUZjUA6AsZpHuQoSKyFXVmIpzLcKX0pDyGZuq+EwTYNjQ9ltbhfu2meWGByH0llff9s+OM9ZL8fgxU/3W9YVjlTxjXpgf8I+BroJEQlV0ESwFsOkjNN/5+4QTuGjLDPddmmzhu80wxasdBzNuyQFB8s4GXDcQVsitwtNWmxtkyFm+RvAMFvlQIuLr27rIKF7SNKOJNATdK1Risv5j12a7GiCq8B4H6SDlCje1wDxsv83PAhSxEH41kVVyVDpi1RbOB3n1I0r4Ks4he0eC53HBj4CQ4qbAhm//2jZN1xaz39sDJEu6gqIZttw7W+TuK8jUOd47iuqpK6JDRbcn2kYRo6mqKEqR8melVo1G5bn3RjGH7O699KnOxBEWmo9E8t6RUV8SGMR6NAVBiE0+wYvJieIx+miLXVWd92rA7kHQKqP0B/sub9VGaPX518NI/OEJlUPH+QUrTamDKw7nXocmO924DeabPiB5FVcreSegJe+WWL2d4tFiwsb0kCffTPfu1Xo=
  template:
    metadata:
      name: docker-registry-secret
      namespace: plenartrend
    type: kubernetes.io/dockerconfigjson

