{
 "title": "Cluster Health",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node) (\n  (1 - avg by(instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[5m]))) * 100\n  * on(instance) group_left(node) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (Node Level)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  ((node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100)\n  * on(instance) group_left(nodename) node_uname_info\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control Plane Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  kube_node_role{role=\"control-plane\"} \n  * on(node) \n  kube_node_status_condition{condition=\"Ready\", status=\"true\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Worker Node Amount",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(\n  kube_node_status_condition{condition=\"Ready\", status=\"true\"} \n  unless on(node) kube_node_role{role=~\"control-plane|master\"}\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Utilization (k3s Level)",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (nodename) (\n  (\n    node_memory_working_set_bytes \n    / \n    on(node) group_left() kube_node_status_allocatable{resource=\"memory\"}\n  ) * 100\n  * on(node) group_left(nodename) label_replace(node_uname_info, \"node\", \"$1\", \"nodename\", \"(.*)\")\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Pressure",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_node_status_condition{condition=\"MemoryPressure\", status=\"true\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Frontend Pods Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"plenartrend-frontend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Instances Online",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 19, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(cnpg_collector_up)", "legendFormat": "__auto" }
   ]
  }
 ]
}