apiVersion: apps/v1
kind: Deployment
metadata:
  name: plenartrend-analytics
  namespace: plenartrend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plenartrend-analytics
  template:
    metadata:
      labels:
        app: plenartrend-analytics
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - plenartrend-analytics
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: analytics
        image: registry.sokutan.de/plenartrend/analytics:0c48218a8299b16a1be7f89acea9a2571b101340
        imagePullPolicy: IfNotPresent
        env:
          - name: DATABASE_USER
            valueFrom:
              secretKeyRef:
                name: postgres-admin-secret
                key: username
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-admin-secret
                key: password
          - name: DATABASE_HOST
            value: "postgresql-db-rw.plenartrend.svc.cluster.local"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: "plenartrenddb"
          - name: PROCESS_START_DATE
            value: "2026-12-31T00:00:00+00:00"
          - name: DEEPSEEK_API_KEY
            valueFrom:
              secretKeyRef:
                name: deepseek-api-key-secret
                key: DEEPSEEK_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"

