---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: deepseek-api-key-secret
  namespace: plenartrend
spec:
  encryptedData:
    DEEPSEEK_API_KEY: AgBqMm1Cy9mQfI0UWz2Un74a/PpJeEXIsJmnSyE50kaOEU7pYGdaF0REGBHokXvJrCQEZJ1zi9NTVN5Q7UhgNKvaPAn4+v3AithZx71UImZ1NtkWdXZKcjStOYxx3pzapvCP7V2UxAALAp/TD2443Zk8o1KdWGi0gqEc0BegNHEYh5A3aFQc4NGAxjWj158EAe5wEiCKJmyeugCyVHnLf8/LKJjyNJ+FL04UPR9M4tkf7I4h3I/mFI+4VjUmnVjWR5piU5eUACvb+gW04zw0aiO7lPl23bCBhaVxS8J+FHKYs1vTguah9iiwCGc78ZjLpPoHlJQlxnKkABFMblvEv2Y37Ul26uib+FrTaVFcPsXGTvDM1ftEY+QQWMyEo4xdv0g1We0QoSk/n0BqLb3KcHjSOr+ZKebeWXkh/1YYir9dxW9OAarkNDXoVvR8Jhvhn7BePyqR1fzFaJ9L2sYiZO/Yyrr73ljrApZDKLsrmLdXr1JvDlKTZC8oe3rwktnKCLOmfnlMINBO5g6DOo5KvZRUC//tCEDLqcOQqoM/gUV2UG6m3sFwTZLK3+K9t5ksHfBIMZoQXUv4Iv0pBNO2wHbM+voIXBbc0yGHF6wpn679RCRmzRZdGIOwdjH9OtkoSu/L8weDLgFuki0smM3tVmn0oPiOBhtEjj7uRfJtNQhDLu7ezoLdzziROT5uhFzs5vwEs3T6entOJzDbwg1Y/j3HrKils1v7mCvHZwNXatjqpPA6UA==
  template:
    metadata:
      name: deepseek-api-key-secret
      namespace: plenartrend
    type: Opaque
