---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-api-key-simon-secret
  namespace: plenartrend
spec:
  encryptedData:
    GEMINI_API_KEY: AgB5ysztLTHziZxTIFM1HM92wviu1/SUejQGGTDxZocbNGGq3L4AM0W0dXsjhky19+glAVU0yvy9lO2IfTgO3BVrpcIJT0EG3a5+z2XgCarxFiBSfaqVr26QP5tn8/hk8Mi5MDW0C3O6Chw4QE45bjBkn0oxHn5fckeg6ePboeX1xURuEEd460G7/bnFblv2tZ8xlZGPNP4tbPpWf7/pLPpcMu2SoG9GspmDbEf5nQFmoyqOOWvaL5t5v2THd5EQUzgSPgN9YxA9R98IONHaFG+cjFi3J0xhlrubv3ClEgy07hf5P+t0xnFeRHcF2rbxAQtHI9jZfOfGk+8fZpD0Xhf4QY9xYCqDsOWdLtvlThL5i5/wDMjhEhM+8p9F3LWnm1dsPexB6JstpDpdpOFyMFBp7iZCXLxYh5iu2Fjd5esS1uki0P/xCm1eifWfcESoJMxWApnTGaHimtAw8p7+QXkEL4eQ+KPK8vJ7FBEoMDhOn6eu+sIonby5PveWvwkrI6jG0n1cXlCckm5HwVPUkyDlu0OIPZldWGe/EQsWLWwBfF6RH2YN/3eCxfY7oK64j39ha8htfSwZ04mplgy2w21/kccdgHZfbXawMpTQa6eHhNxHkfa/e+7oxLeqOodpZE3u9SRUoxwuzprLjEBbPC/g1RFwpu2inaypMny5xn+gb9Txq5QgmohudrLSjosU8znSrBZE+HKa8jdGLTOTRVGN9/wI2R/77oL4FK/a1CtgU0PJw96L8iA=
  template:
    metadata:
      name: gemini-api-key-simon-secret
      namespace: plenartrend
    type: Opaque
