apiVersion: v1
kind: Service
metadata:
  name: plenartrend-frontend
  namespace: plenartrend
  annotations:
    traefik.ingress.kubernetes.io/service.serverstransport: plenartrend-fast-timeout@kubernetescrd
spec:
  selector:
    app: plenartrend-frontend
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  type: ClusterIP

