apiVersion: apps/v1
kind: Deployment
metadata:
  name: plenartrend-frontend
  namespace: plenartrend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: plenartrend-frontend
  template:
    metadata:
      labels:
        app: plenartrend-frontend
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: app
                  operator: In
                  values:
                  - plenartrend-frontend
              topologyKey: kubernetes.io/hostname
      imagePullSecrets:
      - name: docker-registry-secret
      containers:
      - name: frontend
        image: registry.sokutan.de/plenartrend/frontend:ae244131320820290e157f6c66b937601b25c042
        imagePullPolicy: IfNotPresent
        readinessProbe:
          httpGet:
            path: /api/v1/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 3
          failureThreshold: 2
        env:
          - name: API_BASE_URL
            value: "http://plenartrend-crud.plenartrend.svc.cluster.local"
        ports:
        - containerPort: 3000
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "1000m"

