---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-api-key-max-secret
  namespace: plenartrend
spec:
  encryptedData:
    GEMINI_API_KEY: AgBj1NYZhmJTesr1SkooJIHmsD+9YbV+GoQigAJVEUFJA/mVlOR7Axz0QFK7D118witIHW/yOIECDGj55pzl2ECWIIch9/W2T/lxRNn75uLI9YXr9+LTG4Zi9LakJIvcfgfIP4shlmaA4g0pEiOJY8uVgZiuFS3g0LzMuEgyDSpVD6FmiAd++s5UrhhoVIl4etwsqprz/0SsEX6+7uHBq2Z99Gr4xPjXeWhbd3edNxx2lM2+uAxAj7PtD7+jTIlXywk4gqJtl4hNgh3AdyykXoIWH/uUKEzrwBrL6YMdGOqENq5ZgzUCgHGBQCuChW8LsrQZ0UUNH02/KwyjVL5IU7pO0me2sN1FoAnNRZel78npNFqzt74+3FXH5YkGPMCem3fy/43wwERfJAcXr0OQS0t8kT1jvW+p3j4Ev5WmxVO6V9AVSu8tMDehglXzHev7hQbk1bStaeQM8+TQLjnRCgwCW1VhwciThbNc/IQiVJwxdUaxDRdKz2Uqhp+5bJg7BCXI0RrU3CBb6Y0v1JIUMwNitQ474j6nZxQA3+KQYb2YvVyqWHj64yWk+P8NeVIyyoBw7f1SnHxHIWv4XmQACCpaopjETzue6LRuwQD7jIho1ZajJymQOXe6QpV4/TQ3KB3qPC8OxVGxOq7fFvmdMOBXr6nXUEl2YmJM/rJsO/Z9xhQ/nBCOti7i44ck4+9OAGbnP15H4XcHdpYDtKRti4hBlxyIfw/Jv55c1OBynCtC+Jb1RXDAlZI=
  template:
    metadata:
      name: gemini-api-key-max-secret
      namespace: plenartrend
    type: Opaque
