---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-api-key-max-secret
  namespace: plenartrend
spec:
  encryptedData:
    GEMINI_API_KEY: AgAxS7kZFi4SjRh6dLTqhuAOci+c79qbzkCdCYl4JoKyh7iIo3BDQQXy1I2X3W2XZm99YFJl/QjEif8e2Q0IdV23D6YiFqgAjppQW08iJ3ix0gvs9ac33fyHRD8GU5eGc1rLBRbU2yK/wSibKrC2ii2HJlY9ARq6+fPXJUhSfap5pMe5LOQIEjFegXl/7zwRLcLtTosocLXTJ11U/77Ldtgnoat1JDsUEk/XPWLhiwT/iti8IJvbFr6kg0JVa/2a9lWoPra9gZg10WE0gRRZx8NZuJQ0PE+PBVSRVC6hM2nPe/O2BW9VYTWhUSKmKhEm3Dc2DUYr5cUVheOK7/OftWvLShlZPn7vu5E/dYdAyRmkkGSaYyv0EFiUPhLac4k6zU/PJpj8/8PrHodUkLmUmzIC1jTFpitipi0wpScts0F3pXk2ODK/jYros/XGx6DeJ8ZuTxzR1m0zyAUCT/zCa4ooGrvp99g9wDEMZHLN31nTcfJmSQjaRC0k0YVCwhtWSYsx8n9ApwyD9W6ht3cE4zEIfE4LZOi0WxBp0yJ0H3yZ6fPGwgRvVTEDZxdFYMGi0yfpXSJSR1kC/kT5o3bBk+XMTzB2BdBEFoOIGSTH7sd7mdVA0EXm4B+I5+0yPRYR5njjivhhYfThpTPmgFtlDICwxIUluQqcD5+T1bG50xYjmMK/a1Od6iYHcha+xW48SHZ7A8HtGFr+hp7ifrNmPTnOVLP85sQrviRG2jLJ
  template:
    metadata:
      name: gemini-api-key-max-secret
      namespace: plenartrend
    type: Opaque
