---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-api-key-samuel-secret
  namespace: plenartrend
spec:
  encryptedData:
    GEMINI_API_KEY: AgCaULjmwZOtLIwYX+gP9/Gfyi6rYyVNmP8558AbeOAG2XcqlwFVSkHMkHz2aN0lt/wl3rzr1hF+VeOrFlXxL3oIuTYCv7CYcjn/1/V8rib92HftQmYMMIRfZYQGCXKNtlWt2ippWVI8Y+Jb+x+D2egfmtTuEDoC+cGlSWmg/Ecu7r898h4bLwQzXeixjDiYW8mJ3/LfpG+JtR8HnHxmrfHC7HZPrKR2yzKKP16khbBWx7DpGtKDE52axD28HYaLuD+T7kMuUzM/TNq5kBU8DJdcampx4wzmTMO1yvfScH7NVJYJEbrsdDhUPmZw+PrWLJhyCi4BgyI7o1ViX3Zf8ap0vhPt7Nx0T1xdqQON4wyjQJyyTG7ymULLU9czNydJ6VXbpnjDgyLAI2cEVnSfFwuj7I1TKnIIpAH/rV1npdESWwEvzP0ey4XcDcT/M8rMCXBo8IROOEpolRzGlu4VKvgA0rhObp5wzpnQLRv/WfXtaUGg1EV8wp2jbOIdEGNA9MdYRBhpG42GijENeQEiAmH0qN/mgFYn3VU7v87GxdMS2IguuqflxEVijlgDbpExnaP0qiYXaym5YUJ4ZeTwfmy4Gblhn7Pk1jg7rKi3y+zEz7D1hFHgOaPdasoG68qefe6jl/BZqW0yz6mUNCjh56PqLi1dfpBCmLKnNwAPh9P47ce5QUOG8QdqCh0QH9Wk5RMt64SQrJbDffJfZr4UuswT4N8+PhWi+kaBh47iu99M82i4HeUBJSk=
  template:
    metadata:
      name: gemini-api-key-samuel-secret
      namespace: plenartrend
    type: Opaque
