---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gemini-api-key-max-secret
  namespace: plenartrend
spec:
  encryptedData:
    GEMINI_API_KEY: AgA8uAJJn/PpIvV69lnz6j5xbCZHgzw8Wcx+IOq1K0OhaNFmSnVEbpmmK82CBXkDeVgH5JIt09TZRJ4mFtN19YYeN5uSpKd3KoWO4ZCGoM/59c2HUcDcufZpwu++2thKQ1obs8BRcUgnDCMou2A0xIOcbMsG4JQ0+o1p2B2zg99nMy37HQxp41nsqZhcuRa8UvmnHc4bVX78RPPIPj9k4WwtONX3leYDImdGyisNkB4VLZuuznaSCjNDxEUrJY0wMndE9UkKocTqUF7sxjtgsH6Q4L8mpqNUZo+QyPsPsl3Hi+ub1d68LSjXnw73tbQn6qB9/rW0xrFE9Df/5YMmNuX7zX0NxBoWZjvjBvYgJUSoFXZ1t3pJ6KKEO8u6VDPND8GjK3pZPplpkBxL5k/p1qnT2F8ZWnL70hcJkhsxPJmpcON4DVgw3vUzG4GPXjqZaZD8/die+11wIzKcoMqkLrMYqf7m0nhSOOSTgqD/srN8c+NzKZHfnbIKVZQf7AZgea1olt/ikZnFtXjbLbKCsHrC9yeNyZ9SU2pWJTsi/XAH2QqzZFrKbx3W4pdd4TaPXgiMbiS+jL43EBsjUbqYkv8m8D+IZhXPQQqn07QbEME8MpK9r5uZD7JBj9njCIHos/BpUyCshlbR8MLzSQH8Q4P7jiIdy0ok0w4T0pCwseNQOX08m7Ll75YlcBtMb3Qi3Q7GACuyma2Y26rH/y7s90FN8ZSYebx1F2C2BXrApLit5ujTnGXoUVM=
  template:
    metadata:
      name: gemini-api-key-max-secret
      namespace: plenartrend
    type: Opaque
