apiVersion: v1
kind: Service
metadata:
  name: plenartrend-protocol-processor
  namespace: plenartrend
spec:
  selector:
    app: plenartrend-protocol-processor
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP